[runner]
pythonVersion = "3.11"
[theme]
primaryColor = "#ff4444"
backgroundColor = "#0f0f1e"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#f5f5f5"
font = "sans serif"

[browser]
gatherUsageStats = false
